(2023-04-26 13:09:43,283) ERROR /home/kerya/PycharmProjects/NewsPortalSkillfactory/venv/lib/python3.10/site-packages/django/utils/log.py(<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('portal/ListNews.htm, Portal/post_list.html'), <traceback object at 0x7f2ccb7544c0>) Internal Server Error: /news/
Traceback (most recent call last):
  File "/home/kerya/PycharmProjects/NewsPortalSkillfactory/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kerya/PycharmProjects/NewsPortalSkillfactory/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/kerya/PycharmProjects/NewsPortalSkillfactory/venv/lib/python3.10/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/kerya/PycharmProjects/NewsPortalSkillfactory/venv/lib/python3.10/site-packages/django/template/response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/kerya/PycharmProjects/NewsPortalSkillfactory/venv/lib/python3.10/site-packages/django/template/response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
  File "/home/kerya/PycharmProjects/NewsPortalSkillfactory/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: portal/ListNews.htm, Portal/post_list.html
(2023-04-26 13:09:43,284) ERROR /home/kerya/PycharmProjects/NewsPortalSkillfactory/venv/lib/python3.10/site-packages/django/core/servers/basehttp.pyNone "GET /news/ HTTP/1.1" 500 92962
